const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Behaviors.LOS,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.jumpthru,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.jumpthru.Acts.SetEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Mouse.Cnds.OnClick
	];
};
self.C3_JsPropNameTable = [
	{DroneSpawn: 0},
	{Crouch: 0},
	{Health: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Flash: 0},
	{Ivan: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{CrouchBox: 0},
	{Solid: 0},
	{DrillWall: 0},
	{Physics: 0},
	{Drone: 0},
	{Audio: 0},
	{CaveBackground: 0},
	{Button: 0},
	{LineOfSight: 0},
	{SkullCrab: 0},
	{Button2: 0},
	{SoftRespawnBox: 0},
	{ProgressionBox: 0},
	{EndBackground: 0},
	{Sine: 0},
	{Sine2: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Text4: 0},
	{Text5: 0},
	{Text6: 0},
	{Text7: 0},
	{Text8: 0},
	{Text9: 0},
	{Text10: 0},
	{Text11: 0},
	{Text12: 0},
	{Jumpthru: 0},
	{Grate: 0},
	{Text13: 0},
	{Text14: 0},
	{ShadowCaster: 0},
	{CaveFloor: 0},
	{Explodywall: 0},
	{FragileCaveFloor: 0},
	{Splody: 0},
	{Text15: 0},
	{CaveTrim: 0},
	{MusicQueBox: 0},
	{Text16: 0},
	{level2ProgressionBox: 0},
	{CaveCorner: 0},
	{Elevator: 0},
	{DiamondWall1: 0},
	{DiamondWall2: 0},
	{Drill: 0},
	{Dronepack: 0},
	{Spike1: 0},
	{MeatBackground: 0},
	{File1: 0},
	{Text17: 0},
	{File2: 0},
	{Text18: 0},
	{Spike2: 0},
	{Button3: 0},
	{DiamondWall3: 0},
	{Spike3: 0},
	{TiledBackground: 0},
	{Level3progressionBox: 0},
	{File3: 0},
	{TiledBackground2: 0},
	{Text19: 0},
	{Typhon: 0},
	{IvanEnd: 0},
	{DiamondWall4: 0},
	{EndProgressionBox: 0},
	{Button4: 0},
	{File4: 0},
	{File5: 0},
	{File6: 0},
	{File7: 0},
	{Text20: 0},
	{Bullet: 0},
	{TheBloodWorm: 0},
	{BossTriggerBox: 0},
	{Text21: 0},
	{NoteCancel: 0},
	{Text22: 0},
	{Text23: 0},
	{EndBox: 0},
	{EndCutscene: 0},
	{BlackoutBox: 0},
	{T1: 0},
	{Text24: 0},
	{I1: 0},
	{T2: 0},
	{Sprite: 0},
	{Text25: 0},
	{Text26: 0},
	{tg: 0},
	{Text27: 0},
	{dialoguecollision1: 0},
	{Dialogue: 0},
	{dialoguecollision2: 0},
	{dialogue2: 0},
	{dialoguecollision3: 0},
	{Dialogue3: 0}
];

self.InstanceType = {
	Ivan: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	CrouchBox: class extends self.ISpriteInstance {},
	DrillWall: class extends self.ISpriteInstance {},
	Drone: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	CaveBackground: class extends self.ITiledBackgroundInstance {},
	Button: class extends self.ISpriteInstance {},
	SkullCrab: class extends self.ISpriteInstance {},
	Button2: class extends self.ISpriteInstance {},
	SoftRespawnBox: class extends self.ISpriteInstance {},
	ProgressionBox: class extends self.ISpriteInstance {},
	EndBackground: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Text8: class extends self.ITextInstance {},
	Text9: class extends self.ITextInstance {},
	Text10: class extends self.ITextInstance {},
	Text11: class extends self.ITextInstance {},
	Text12: class extends self.ITextInstance {},
	Grate: class extends self.ISpriteInstance {},
	Text13: class extends self.ITextInstance {},
	Text14: class extends self.ITextInstance {},
	CaveFloor: class extends self.ITiledBackgroundInstance {},
	Explodywall: class extends self.ISpriteInstance {},
	FragileCaveFloor: class extends self.ITiledBackgroundInstance {},
	Splody: class extends self.ISpriteInstance {},
	Text15: class extends self.ITextInstance {},
	CaveTrim: class extends self.ITiledBackgroundInstance {},
	MusicQueBox: class extends self.ISpriteInstance {},
	Text16: class extends self.ITextInstance {},
	level2ProgressionBox: class extends self.ISpriteInstance {},
	CaveCorner: class extends self.ISpriteInstance {},
	Elevator: class extends self.ISpriteInstance {},
	DiamondWall1: class extends self.ITiledBackgroundInstance {},
	DiamondWall2: class extends self.ITiledBackgroundInstance {},
	Drill: class extends self.ISpriteInstance {},
	Dronepack: class extends self.ISpriteInstance {},
	Spike1: class extends self.ISpriteInstance {},
	MeatBackground: class extends self.ITiledBackgroundInstance {},
	File1: class extends self.ISpriteInstance {},
	Text17: class extends self.ITextInstance {},
	File2: class extends self.ISpriteInstance {},
	Text18: class extends self.ITextInstance {},
	Spike2: class extends self.ISpriteInstance {},
	Button3: class extends self.ISpriteInstance {},
	DiamondWall3: class extends self.ITiledBackgroundInstance {},
	Spike3: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Level3progressionBox: class extends self.ISpriteInstance {},
	File3: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Text19: class extends self.ITextInstance {},
	Typhon: class extends self.ISpriteInstance {},
	IvanEnd: class extends self.ISpriteInstance {},
	DiamondWall4: class extends self.ITiledBackgroundInstance {},
	EndProgressionBox: class extends self.ISpriteInstance {},
	Button4: class extends self.ISpriteInstance {},
	File4: class extends self.ISpriteInstance {},
	File5: class extends self.ISpriteInstance {},
	File6: class extends self.ISpriteInstance {},
	File7: class extends self.ISpriteInstance {},
	Text20: class extends self.ITextInstance {},
	TheBloodWorm: class extends self.ISpriteInstance {},
	BossTriggerBox: class extends self.ISpriteInstance {},
	Text21: class extends self.ITextInstance {},
	NoteCancel: class extends self.ISpriteInstance {},
	Text22: class extends self.ITextInstance {},
	Text23: class extends self.ITextInstance {},
	EndBox: class extends self.ISpriteInstance {},
	EndCutscene: class extends self.ISpriteInstance {},
	BlackoutBox: class extends self.ISpriteInstance {},
	T1: class extends self.ITextInstance {},
	Text24: class extends self.ITextInstance {},
	I1: class extends self.ITextInstance {},
	T2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text25: class extends self.ITextInstance {},
	Text26: class extends self.ITextInstance {},
	tg: class extends self.ITextInstance {},
	Text27: class extends self.ITextInstance {},
	dialoguecollision1: class extends self.ISpriteInstance {},
	Dialogue: class extends self.ITextInstance {},
	dialoguecollision2: class extends self.ISpriteInstance {},
	dialogue2: class extends self.ITextInstance {},
	dialoguecollision3: class extends self.ISpriteInstance {},
	Dialogue3: class extends self.ITextInstance {}
}