const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.gamepad,
		C3.Plugins.Audio,
		C3.Behaviors.LOS,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{GreyTileBackGround: 0},
	{Solid: 0},
	{Counter: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{DestroyOutsideLayout: 0},
	{Bullet: 0},
	{Timer: 0},
	{Flash: 0},
	{EvilBaguette: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Gamepad: 0},
	{TIMMYINDAWINDOW: 0},
	{LILCREEPERAHMANNNNNNNN: 0},
	{Audio: 0},
	{Health: 0},
	{Alive: 0},
	{LineOfSight: 0},
	{GoodButters: 0},
	{Healthbar: 0},
	{Fridge: 0},
	{KillBox: 0},
	{Sine: 0},
	{HealingApple: 0},
	{Carrotspear: 0},
	{CrackerSpike1: 0},
	{CrackerSpike2: 0},
	{CrackerSpike3: 0},
	{Cookie1: 0},
	{Cookie2: 0},
	{Movement: 0},
	{BreadRoll: 0},
	{BreadrollLimiter: 0},
	{CrackerSpikes: 0},
	{Cookies: 0},
	{DashReady: 0},
	{Dashing: 0},
	{MagicTophat: 0},
	{Spear: 0}
];

self.InstanceType = {
	GreyTileBackGround: class extends self.ITiledBackgroundInstance {},
	Counter: class extends self.ISpriteInstance {},
	EvilBaguette: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	TIMMYINDAWINDOW: class extends self.ISpriteInstance {},
	LILCREEPERAHMANNNNNNNN: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	GoodButters: class extends self.ISpriteInstance {},
	Healthbar: class extends self.ISpriteInstance {},
	Fridge: class extends self.ISpriteInstance {},
	KillBox: class extends self.ISpriteInstance {},
	HealingApple: class extends self.ISpriteInstance {},
	Carrotspear: class extends self.ISpriteInstance {},
	CrackerSpike1: class extends self.ISpriteInstance {},
	CrackerSpike2: class extends self.ISpriteInstance {},
	CrackerSpike3: class extends self.ISpriteInstance {},
	Cookie1: class extends self.ISpriteInstance {},
	Cookie2: class extends self.ISpriteInstance {},
	BreadRoll: class extends self.ISpriteInstance {},
	BreadrollLimiter: class extends self.ISpriteInstance {},
	CrackerSpikes: class extends self.ISpriteInstance {},
	Cookies: class extends self.ISpriteInstance {}
}