const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Acts.SetJumpStrength
	];
};
self.C3_JsPropNameTable = [
	{Portal: 0},
	{Portal2: 0},
	{Portal3: 0},
	{Portal4: 0},
	{Arrow: 0},
	{Arrow2: 0},
	{Text: 0},
	{Story: 0},
	{Pathfinding: 0},
	{Bullet: 0},
	{Enemy: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Scientist: 0},
	{Coin: 0},
	{NoiseLine: 0},
	{Speaker: 0},
	{DoubleJump: 0},
	{SuperJump: 0},
	{SpeedUpgrade: 0},
	{Solid: 0},
	{SecretFloor: 0},
	{PlayerSpawn2: 0},
	{Flag: 0},
	{InvisibalFloor: 0},
	{Death: 0},
	{TiledBackground: 0},
	{Laser: 0},
	{MonitorScreen: 0},
	{TutorialFlag: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Text2: 0},
	{Sprite: 0}
];

self.InstanceType = {
	Portal: class extends self.ISpriteInstance {},
	Portal2: class extends self.ISpriteInstance {},
	Portal3: class extends self.ISpriteInstance {},
	Portal4: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Arrow2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Story: class extends self.ITextInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Scientist: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	NoiseLine: class extends self.ISpriteInstance {},
	Speaker: class extends self.ISpriteInstance {},
	DoubleJump: class extends self.ISpriteInstance {},
	SuperJump: class extends self.ISpriteInstance {},
	SpeedUpgrade: class extends self.ISpriteInstance {},
	Platform: class extends self.ISpriteInstance {},
	SecretFloor: class extends self.ISpriteInstance {},
	PlayerSpawn2: class extends self.ISpriteInstance {},
	Flag: class extends self.ISpriteInstance {},
	InvisibalFloor: class extends self.ISpriteInstance {},
	Death: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Laser: class extends self.ISpriteInstance {},
	MonitorScreen: class extends self.ISpriteInstance {},
	TutorialFlag: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {}
}